### PR TITLE
Sorting #RB-544

### PR DESCRIPTION
**Pull request by hugifix**
Please add the jira number (#RB-544) to the commit merge message

### CODE REVIEW

**Comment by hugifix** [comment]
Managed the default sortDirection. Ready to merge after review.

**Comment by istvank** [comment]
Hi, I added some documentation. The element doesn't seem to work as intended, there are multiple issues that need change before merging:
a) When changing the sorting property, I expect the previous/next buttons to reset. However they don't.
b) When switching pages, two requests are sent.
c) In the rare (?) case that `number_of_requirements mod per_page = 0` (for example on the demo page currently 😄 ) the last "Next" button leads to an empty page. Why don't we evaluate the link-headers?

Besides, changing the sort direction for Date sorting doesn't change anything - that's a case for better demo data.

**Comment by hugifix** [comment]
- I fixed issue b).
- Issue c) is not so easy. See the message I sent you in slack. I now try to get the custom header, if this is not working because CORS is not enabled I switch back to old logic. I could not try the CORS path, because I could not enable it. Do you worked with the custom header fields in ReqBaz before?
- Issue a) runs in a loop. Problem is that inside the _computeOptions I change the options again. Like setting page = 0 if other options changes (e.g. new sorting) and resetting sortDirection if sorting changed. But changing this options inside _computeOptions does trigger the _computeOptions again. I thought about a nice solution but the only solution I came up used observer + computed and many nested ifs. No nice code. Do you have any solution for this problem in your mind?

**DO NOT MERGE. Task a) is not solved!**

**Comment by istvank** [comment]
About a): What does
```javascript
// reset page if one of the other parameters changed
if (this._lastPage === page) {
  this.page = page;
  page = 0;
}
this._lastPage = page;
```
do? Does it make sense? Unfortunately, _lastPage is not documented. I am working on it, so please don't commit currently.

**Comment by hugifix** [comment]
I thought if any parameter without page is changing I reset the page. _lastPage is an internal variable to remember the _lastPage. Same as lastSortDirection. Both is not working correct!

**Comment by istvank** [comment]
Should work the same as in https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/blob/development/elements/requirements-list.html

**Comment by istvank** [comment]
I checked it. It basically works the same - the request is `auto` as well, but it is sent only once. However,
```javascript
this.page = page;
```
really didn't make sense. Changed the block to
```javascript
if (this._lastPage === page) {
  this.page = 0;
}
this._lastPage = this.page;
```
Which works and only results in one request.

**Comment by hugifix** [comment]
But
```javascript
if (['date', 'vote', 'comment', 'follower'].indexOf(sorting) >= 0) {
  this._sortDirection = '-';
  sortDirection = '-';
} else {
  this._sortDirection = '+';
  sortDirection = '+';
}
this._sortDirection =
```
... can also lead to multiple requests I guess.

**Comment by istvank** [comment]
Can you please check whether a) works now? Especially if the _last parameters are set correctly. I guess we can leave out c) here and fix it in another iteration, since there are backend things to solve for it.

**Comment by istvank** [comment]
I formatted your code in the last comment as I couldn't read it. Where is that code from, anyways?

**Comment by istvank** [comment]
Okay, it's from requirements-grid. It doesn't lead to multiple requests as Polymer seems to wait till the last compute operation ran on that property.

**Comment by hugifix** [comment]
Works fine. Thanks for your help. You can merge.

**Pull request merged**
